apiVersion: v1
kind: ServiceAccount
metadata:
  name: tarka
  namespace: tarka
  annotations:
    # IRSA role ARN (EKS). Replace this.
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/tarka-irsa-role
